### ISSUE TITLE
I have a pre-defined map, can I use this application?

### ISSUE THREAD

**Issue by cmercmad** [abdulkadrtr/ROS2-PurePursuitControl-PathPlanning-Tracking#1]
Hi,

I'm doing my first project about autonomous vehicles using ROS, so I'm now learning how to use ROS and the posibilities I have. I want the vehicle to follow a defined path (two straight lines and two curves), so the route is known and repetitive. 

If I have understood correctly, this applictation employs the SLAM Toolbox to get the map. In my case, I have UTMx and UTMy coordinates of the circuit/path. So, do you think that I can use this application having a known circuit?

Thanks.

**Comment by abdulkadrtr** [comment]
Hi, 
This package finds a path to the target point on the map and follows that path. The robot model used here is a differential drive robot model. Vehicle models have Ackermann drive model. Differential drive and Ackermann drive are different from each other. For example, in this package, the robot can rotate around itself, but a car cannot perform this movement. Firstly, because of this reason, you cannot use this package in your project.
I recommend you examine the Ackermann drive model. Have good work.
